/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenMergeWithUserDefinedAdapter extends Token
{
    public TTokenMergeWithUserDefinedAdapter()
    {
        super.setText("merge-with-user-defined-mapping:");
    }

    public TTokenMergeWithUserDefinedAdapter(int line, int pos)
    {
        super.setText("merge-with-user-defined-mapping:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenMergeWithUserDefinedAdapter(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenMergeWithUserDefinedAdapter(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenMergeWithUserDefinedAdapter text.");
    }
}
