/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorTwoPowDInt extends Token
{
    public TTokenVectorTwoPowDInt()
    {
        super.setText("vector2PowD(int):");
    }

    public TTokenVectorTwoPowDInt(int line, int pos)
    {
        super.setText("vector2PowD(int):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorTwoPowDInt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorTwoPowDInt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorTwoPowDInt text.");
    }
}
