/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenEventMapping extends Token
{
    public TTokenEventMapping()
    {
        super.setText("event-mapping:");
    }

    public TTokenEventMapping(int line, int pos)
    {
        super.setText("event-mapping:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenEventMapping(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenEventMapping(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenEventMapping text.");
    }
}
