#!/bin/csh
#SBATCH -p seq6.q
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --output={OUTPUT_FILE}
#SBATCH -t 30:00:00

module purge
module load intel/xe_2015.2
module load intelmpi/intel/5.0.3
module load slurm
module unload gcc/4.9.1
module load gcc/4.9.1

setenv OMP_NUM_THREADS 1

srun {RUN}
