/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorFivePowDDouble extends Token
{
    public TTokenVectorFivePowDDouble()
    {
        super.setText("intergrid-operator(double):");
    }

    public TTokenVectorFivePowDDouble(int line, int pos)
    {
        super.setText("intergrid-operator(double):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorFivePowDDouble(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorFivePowDDouble(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorFivePowDDouble text.");
    }
}
