/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorFivePowDInt extends Token
{
    public TTokenVectorFivePowDInt()
    {
        super.setText("intergrid-operator(int):");
    }

    public TTokenVectorFivePowDInt(int line, int pos)
    {
        super.setText("intergrid-operator(int):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorFivePowDInt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorFivePowDInt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorFivePowDInt text.");
    }
}
