/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenDastgenFile extends Token
{
    public TTokenDastgenFile()
    {
        super.setText("dastgen-file:");
    }

    public TTokenDastgenFile(int line, int pos)
    {
        super.setText("dastgen-file:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenDastgenFile(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenDastgenFile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenDastgenFile text.");
    }
}
