/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenScalarDouble extends Token
{
    public TTokenScalarDouble()
    {
        super.setText("scalar(double):");
    }

    public TTokenScalarDouble(int line, int pos)
    {
        super.setText("scalar(double):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenScalarDouble(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenScalarDouble(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenScalarDouble text.");
    }
}
