#!/bin/csh
#SBATCH -p test.q
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --output={OUTPUT_FILE}
#SBATCH -t 1:00:00
#SBATCH --exclusive

module purge
module load intel/xe_2015.2
module load intelmpi/intel/5.0.3
module load slurm
module load likwid/4.1

setenv OMP_NUM_THREADS 2

srun {RUN}
