#!/bin/csh
#SBATCH -p par6.q
#SBATCH -N 8
#SBATCH --ntasks-per-node=16

#SBATCH -t 06:00:00
#SBATCH --exclusive

module purge
module load intel/xe_2015.2
module load intelmpi/intel/5.0.3
module load slurm
module load sge
module load valgrind/3.9.0

time mpirun ./tribal
