/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorFivePowDComplex extends Token
{
    public TTokenVectorFivePowDComplex()
    {
        super.setText("intergrid-operator(complex):");
    }

    public TTokenVectorFivePowDComplex(int line, int pos)
    {
        super.setText("intergrid-operator(complex):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorFivePowDComplex(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorFivePowDComplex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorFivePowDComplex text.");
    }
}
