/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenStencilDouble extends Token
{
    public TTokenStencilDouble()
    {
        super.setText("stencil(double):");
    }

    public TTokenStencilDouble(int line, int pos)
    {
        super.setText("stencil(double):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenStencilDouble(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenStencilDouble(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenStencilDouble text.");
    }
}
