/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenScalarComplex extends Token
{
    public TTokenScalarComplex()
    {
        super.setText("scalar(complex):");
    }

    public TTokenScalarComplex(int line, int pos)
    {
        super.setText("scalar(complex):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenScalarComplex(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenScalarComplex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenScalarComplex text.");
    }
}
