# C files
C_SRC= 
CPP_SRC = delta.cpp hybrid.cpp bf.cpp penalty.cpp

CC=gcc
CXX=g++

# Program name
EXE=delta

# Floating point type
REAL=double

# Debug version
DEBUG=no

# Do the rest
include common.mk
