/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenHeapDastgenFile extends Token
{
    public TTokenHeapDastgenFile()
    {
        super.setText("heap-dastgen-file:");
    }

    public TTokenHeapDastgenFile(int line, int pos)
    {
        super.setText("heap-dastgen-file:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenHeapDastgenFile(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenHeapDastgenFile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenHeapDastgenFile text.");
    }
}
