/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorTwoPowDComplex extends Token
{
    public TTokenVectorTwoPowDComplex()
    {
        super.setText("vector2PowD(complex):");
    }

    public TTokenVectorTwoPowDComplex(int line, int pos)
    {
        super.setText("vector2PowD(complex):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorTwoPowDComplex(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorTwoPowDComplex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorTwoPowDComplex text.");
    }
}
