/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorTwoPowDDouble extends Token
{
    public TTokenVectorTwoPowDDouble()
    {
        super.setText("vector2PowD(double):");
    }

    public TTokenVectorTwoPowDDouble(int line, int pos)
    {
        super.setText("vector2PowD(double):");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorTwoPowDDouble(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorTwoPowDDouble(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorTwoPowDDouble text.");
    }
}
