#ifndef _PEANO_PARALLEL_MESSAGES_LOADBALANCINGMESSAGE_H
#define _PEANO_PARALLEL_MESSAGES_LOADBALANCINGMESSAGE_H

#include "peano/utils/Globals.h"
#include "tarch/compiler/CompilerSpecificSettings.h"
#include "peano/utils/PeanoOptimisations.h"
#ifdef Parallel
	#include "tarch/parallel/Node.h"
#endif
#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <complex>
#include <string>
#include <iostream>

namespace peano {
   namespace parallel {
      namespace messages {
         class LoadBalancingMessage;
         class LoadBalancingMessagePacked;
      }
   }
}

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 09-02-2014 14:40
 *
 * @date   31/03/2018 16:42
 */
class peano::parallel::messages::LoadBalancingMessage { 
   
   public:
      
      typedef peano::parallel::messages::LoadBalancingMessagePacked Packed;
      
      struct PersistentRecords {
         int _loadBalancingFlag;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const int& loadBalancingFlag);
         
         /**
          * Generated
          */
          int getLoadBalancingFlag() const ;
         
         /**
          * Generated
          */
          void setLoadBalancingFlag(const int& loadBalancingFlag) ;
         
         
      };
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         LoadBalancingMessage();
         
         /**
          * Generated
          */
         LoadBalancingMessage(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         LoadBalancingMessage(const int& loadBalancingFlag);
         
         /**
          * Generated
          */
         virtual ~LoadBalancingMessage();
         
         /**
          * Generated
          */
          int getLoadBalancingFlag() const ;
         
         /**
          * Generated
          */
          void setLoadBalancingFlag(const int& loadBalancingFlag) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         LoadBalancingMessagePacked convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderDestinationRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            enum class ExchangeMode { Blocking, NonblockingWithPollingLoopOverTests, LoopOverProbeWithBlockingReceive };
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            #endif
   
};

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 09-02-2014 14:40
 *
 * @date   31/03/2018 16:42
 */
class peano::parallel::messages::LoadBalancingMessagePacked { 
   
   public:
      
      struct PersistentRecords {
         int _loadBalancingFlag;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const int& loadBalancingFlag);
         
         /**
          * Generated
          */
          int getLoadBalancingFlag() const ;
         
         /**
          * Generated
          */
          void setLoadBalancingFlag(const int& loadBalancingFlag) ;
         
         
      };
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         LoadBalancingMessagePacked();
         
         /**
          * Generated
          */
         LoadBalancingMessagePacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         LoadBalancingMessagePacked(const int& loadBalancingFlag);
         
         /**
          * Generated
          */
         virtual ~LoadBalancingMessagePacked();
         
         /**
          * Generated
          */
          int getLoadBalancingFlag() const ;
         
         /**
          * Generated
          */
          void setLoadBalancingFlag(const int& loadBalancingFlag) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         LoadBalancingMessage convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderDestinationRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            enum class ExchangeMode { Blocking, NonblockingWithPollingLoopOverTests, LoopOverProbeWithBlockingReceive };
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            #endif
   
};

#endif

