#!/bin/csh
#SBATCH -p par6.q
#SBATCH -N 1
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --output={OUTPUT_FILE}
#SBATCH -t 20:00:00
#SBATCH --exclusive

module purge
module load intel/xe_2015.2

module load slurm
module unload gcc/4.9.1
module load gcc/4.9.1

setenv OMP_NUM_THREADS 16

srun {RUN}
